load("//bazel:crashpad.bzl", "crashpad_cc_library")

package(default_visibility = ["//visibility:public"])

# :context is the only part of snapshot that minidump may depend on.
crashpad_cc_library(
    name = "context",
    srcs = ["cpu_context.cc"],
    hdrs = [
        "cpu_architecture.h",
        "cpu_context.h",
    ],
    deps = [
        "//third_party/mini_chromium/mini_chromium/base",
        "//util",
    ],
)

crashpad_cc_library(
    name = "snapshot",
    srcs = [
        "annotation_snapshot.cc",
        "capture_memory.cc",
        "crashpad_info_client_options.cc",
        "handle_snapshot.cc",
        "memory_snapshot.cc",
        "minidump/exception_snapshot_minidump.cc",
        "minidump/memory_snapshot_minidump.cc",
        "minidump/minidump_annotation_reader.cc",
        "minidump/minidump_context_converter.cc",
        "minidump/minidump_simple_string_dictionary_reader.cc",
        "minidump/minidump_string_list_reader.cc",
        "minidump/minidump_string_reader.cc",
        "minidump/module_snapshot_minidump.cc",
        "minidump/process_snapshot_minidump.cc",
        "minidump/system_snapshot_minidump.cc",
        "minidump/thread_snapshot_minidump.cc",
        "unloaded_module_snapshot.cc",
    ] + select({
        "@platforms//os:linux": [
            "posix/timezone.cc",
            "linux/capture_memory_delegate_linux.cc",
            "linux/cpu_context_linux.cc",
            "linux/debug_rendezvous.cc",
            "linux/exception_snapshot_linux.cc",
            "linux/process_reader_linux.cc",
            "linux/process_snapshot_linux.cc",
            "linux/system_snapshot_linux.cc",
            "linux/thread_snapshot_linux.cc",
            "sanitized/memory_snapshot_sanitized.cc",
            "sanitized/module_snapshot_sanitized.cc",
            "sanitized/process_snapshot_sanitized.cc",
            "sanitized/sanitization_information.cc",
            "sanitized/thread_snapshot_sanitized.cc",
            "crashpad_types/crashpad_info_reader.cc",
            "crashpad_types/image_annotation_reader.cc",
            "elf/elf_dynamic_array_reader.cc",
            "elf/elf_image_reader.cc",
            "elf/elf_symbol_table_reader.cc",
            "elf/module_snapshot_elf.cc",
        ],
        "//conditions:default": [],
    }) + select({
        "@platforms//cpu:x86_64": ["x86/cpuid_reader.cc"],
        "//conditions:default": [],
    }),
    hdrs = [
        "annotation_snapshot.h",
        "capture_memory.h",
        "crashpad_info_client_options.h",
        "exception_snapshot.h",
        "handle_snapshot.h",
        "memory_map_region_snapshot.h",
        "memory_snapshot.h",
        "memory_snapshot_generic.h",
        "minidump/exception_snapshot_minidump.h",
        "minidump/memory_snapshot_minidump.h",
        "minidump/minidump_annotation_reader.h",
        "minidump/minidump_context_converter.h",
        "minidump/minidump_simple_string_dictionary_reader.h",
        "minidump/minidump_stream.h",
        "minidump/minidump_string_list_reader.h",
        "minidump/minidump_string_reader.h",
        "minidump/module_snapshot_minidump.h",
        "minidump/process_snapshot_minidump.h",
        "minidump/system_snapshot_minidump.h",
        "minidump/thread_snapshot_minidump.h",
        "module_snapshot.h",
        "process_snapshot.h",
        "snapshot_constants.h",
        "system_snapshot.h",
        "thread_snapshot.h",
        "unloaded_module_snapshot.h",
    ] + select({
        "@platforms//os:linux": [
            "posix/timezone.h",
            "linux/capture_memory_delegate_linux.h",
            "linux/cpu_context_linux.h",
            "linux/debug_rendezvous.h",
            "linux/exception_snapshot_linux.h",
            "linux/process_reader_linux.h",
            "linux/process_snapshot_linux.h",
            "linux/signal_context.h",
            "linux/system_snapshot_linux.h",
            "linux/thread_snapshot_linux.h",
            "sanitized/memory_snapshot_sanitized.h",
            "sanitized/module_snapshot_sanitized.h",
            "sanitized/process_snapshot_sanitized.h",
            "sanitized/sanitization_information.h",
            "sanitized/thread_snapshot_sanitized.h",
            "crashpad_types/crashpad_info_reader.h",
            "crashpad_types/image_annotation_reader.h",
            "elf/elf_dynamic_array_reader.h",
            "elf/elf_image_reader.h",
            "elf/elf_symbol_table_reader.h",
            "elf/module_snapshot_elf.h",
        ],
        "//conditions:default": [],
    }) + select({
        "@platforms//cpu:x86_64": ["x86/cpuid_reader.h"],
        "//conditions:default": [],
    }),
    deps = [
        ":context",
        "//client:common",
        "//compat",
        "//minidump:format",
        "//third_party/mini_chromium/mini_chromium/base",
        "//util",
    ],
)
